final Map<String, String> currencyDescriptions = {
  'USD': 'Dólar Americano',
  'EUR': 'Euro',
  'BRL': 'Real Brasileiro',
  'GBP': 'Libra Esterlina',
  'JPY': 'Iene Japonês',
  'AUD': 'Dólar Australiano',
  'CAD': 'Dólar Canadense',
  'CHF': 'Franco Suíço',
  'CNY': 'Yuan Chinês',
  'SEK': 'Coroa Sueca',
  'NZD': 'Dólar Neozelandês',
  'MXN': 'Peso Mexicano',
  'SGD': 'Dólar de Cingapura',
  'HKD': 'Dólar de Hong Kong',
  'NOK': 'Coroa Norueguesa',
  'KRW': 'Won Sul-Coreano',
  'TRY': 'Lira Turca',
};
